import { Bench } from "tinybench";
import Rubiks3Cube from "../../src/RubiksCube.js";

const bench = new Bench({
    name: "Initial benchmark",
    time: 1000
})

function encryptMessage(plaintext, key) {
    let ciphertext = "ENC:";
    let j = 0;

    for (let i = 0; i < Math.ceil(plaintext.length / 54); i++) {
        let cube = new Rubiks3Cube();
        cube.writeTextToCube(plaintext.slice(j, j + 54));
        cube.executeMoves(key);
        j += 54;
        ciphertext += cube.readTextFromCube();
    }

    return ciphertext;
}

function decryptMessage(ciphertext, inversekey) {
    let j = 0;
    let plaintext = "";
    for (let i = 0; i < Math.ceil(ciphertext.length / 54); i++) {
        let cube = new Rubiks3Cube();
        cube.writeTextToCube(ciphertext.slice(j, j + 54));
        cube.executeMoves(inversekey);
        j += 54;
        plaintext += cube.readTextFromCube()
    }
    return plaintext;
}

let key = Rubiks3Cube.generateRandomMoves(10);
let inversekey = Rubiks3Cube.generateInverseMoves(key);
let cipher = null

bench.add('Encrypt (54 letters)', () => {
    cipher = encryptMessage("She quickly walked down the bright and very long hallw", key);
}).add('Decrypt (54 letters)', () => {
    decryptMessage(cipher, inversekey);
}).add('Encrypt (540 letters)', () => {
    cipher = encryptMessage("She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall", key);
}).add('Decrypt (540 letters)', () => {
    decryptMessage(cipher, inversekey);
}).add('Encrypt (5400 letters)', () => {
    cipher = encryptMessage(`She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall`, key)
}).add('Decrypt (5400 letters)', () => {
    decryptMessage(cipher, inversekey);
}).add('Encrypt (54000 letters)', () => {
    cipher = encryptMessage(`She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall
She quickly walked down the bright and very long hallw She quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hallwShe quickly walked down the bright and very long hall`, key)
}).add('Decrypt (54000 letters)',()=>{
    decryptMessage(cipher, inversekey)
})
await bench.run();

console.log(bench.name);
console.log(bench.table());